name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: gh-pages-workflow
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Gulp build
        run: gulp

      - name: Copy files
        run: |
          cp CNAME dist/CNAME

      - name: Deploy master branch to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean: true
          commit-message: Update hub